#+title: Exercise with /Gaia/ DR3 data
#+author: [[mrenzo@flatironinstitute.org][Mathieu Renzo]]


These are notes on how to retrieve the /Gaia/ DR3 data and play with
them. With no coding experience, the playground can also be directly
the FlatironHub python interface.

You can download from [FlatironHub] (fractions of) the /Gaia/ DR3
dataset as =csv= (comma separated values), which can be open in a spreadsheet.


** Idea of exercises

*** Find the peculiar velocity of the Sun

  Download a sample of stars "nearby" and find the velocity common to
  all of those (which is a reflection of the peculiar motion of the Sun)

*** Distribution of velocities of all the bright stars

  Similar to the figure [[https://ui.adsabs.harvard.edu/abs/2011MNRAS.410..190T/abstract][Tetzlaff et al. 2011]], but using /Gaia/ data
  rather than /Gaia/'s predecessor /Hipparcos/.

*** Galactic rotation

  Visualize the rotation of the Galaxy with the absolute proper
  motions of a large sample of /Gaia/ data

*** Find structures

**** Large Magellanic Cloud (LMC):
    - RA range: Approximately 76 to 94 degrees
    - DEC range: Approximately -74 to -66 degrees
    - parallax: negative or zero
**** Small Magellanic Cloud (SMC):
    - RA range: Approximately 10 to 22 degrees
    - DEC range: Approximately -76 to -66 degrees
    - parallax: negative or zero
**** Orion Nebula:
    - RA range: Approximately 83.5 to 84.5 degrees
    - DEC range: Approximately -6.5 to -5.5 degrees
    - parallax:  2210 - 2700 milliarcseconds

** Image credits

*** Orion Nebula composite
  Downloaded from NSF's Noirlab.
  [[https://noirlab.edu/public/products/education/edu024/][source zip]]
